jobs:
- name: report-federalist-changes
  plan:
  - in_parallel:
    - get: compliance-check-cron
      trigger: true
    - get: report-federalist
    - get: terraform-yaml

  - task: query-cloudtrail
    tags: [iaas]
    file: report-federalist/query-cloudtrail.yml
    params:
      FED_AWS_ACCESS_KEY_ID: ((fed-federalist-aws-access-key-id))
      FED_AWS_SECRET_ACCESS_KEY: ((fed-federalist-aws-secret-access-key))
      OLD_BUCKETS: ((old-buckets))

  - task: send-report
    file: report-federalist/send-report.yml
    params:
      SMTP_HOST: ((smtp-host))
      SMTP_PASS: ((smtp-pass))
      SMTP_USER: ((smtp-user))
      MAIL_FROM: ((mail-from))
      MAIL_TO: ((mail-to))

resources:
- name: report-federalist
  type: git
  source:
    uri: ((report-federalist-git-url))
    branch: ((report-federalist-git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: compliance-check-cron
  type: cron-resource
  source:
    expression: 0 15 * * 5  # Run at 3PM EST on Friday
    location: "America/New_York"

- name: terraform-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket-tooling))
    versioned_file: ((tf-state-file-tooling))
    region_name: ((aws-region))

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
