jobs:
- name: report-federalist-changes
  plan:
  - aggregate:
    - get: compliance-check-cron
      trigger: true
    - get: report-federalist
  - task: screenshot-cloudtrail
    tags: [iaas]
    file: report-federalist/screenshot-cloudtrail.yml
    params:
      BUCKET: {{federalist-bucket}}
  - task: convert-to-gif
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: asciinema/asciicast2gif
      inputs:
        - name: recording
      outputs:
        - name: gif-recording
      params:
        DEBUG: 1
      run:
        path: sh
        args:
        - -e
        - -x
        - -c
        - /app/asciicast2gif -s .5 -S 1 -w 120 -h 32 recording/federalist-report.json gif-recording/federalist-report.gif
  - task: send-report
    file: report-federalist/send-report.yml
    params:
      SMTP_HOST: {{smtp-host}}
      SMTP_PASS: {{smtp-pass}}
      SMTP_USER: {{smtp-user}}
      MAIL_FROM: {{mail-from}}
      MAIL_TO: {{mail-to}}

resources:
- name: report-federalist
  type: git
  source:
    uri: {{report-federalist-git-url}}
    branch: {{report-federalist-git-branch}}

- name: compliance-check-cron
  type: cron-resource
  source:
    expression: 0 15 * * 5 # Run at 3PM EST on Friday
    location: "America/New_York"

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
